logging:
    level:
        ROOT: WARN
        hut34: DEBUG
        org.springframework: INFO
        # Log how long scanning objectify entity classes takes
        org.springframework.contrib.gae.objectify.config.ObjectifyEntityScanner: DEBUG
        # Detailed startup logs
        org.springframework.boot.StartupInfoLogger: DEBUG
        # Below is to log servlet response mapping exceptions
        org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: TRACE

app:
    name: Hut34 Wallet
    id: ${com.google.appengine.application.id:no_app_id}
    environment: ${com.google.appengine.runtime.environment:Local Test}
    host: '- no host -'

tasks:
    email:
        queue: default
        invite: /task/send-user-invite

spring:
    mail:
        default-encoding: UTF-8

    jackson:
        serialization.WRITE_DATES_AS_TIMESTAMPS: false
        default-property-inclusion: non_null

    thymeleaf:
        prefix: /WEB-INF/th/
        mode: LEGACYHTML5

mailSender:
    fromAddress: 'hut34-wallet@email.org'

oauth:
  google:
    client:
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
